baseURL = "https://iredis.io/"
languageCode = "en-us"
title = "iredis"
description = "Interactive Redis: A Terminal Client for Redis with AutoCompletion and Syntax Highlighting."
theme = "github-project-landing-page"
