baseURL = "https://iredis.io/"
languageCode = "en-us"
title = "iredis"
description = "Interactive Redis: A Terminal Client for Redis with AutoCompletion and Syntax Highlighting."
theme = "vanilla-bootstrap-hugo-theme"

# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Github"
    pre = "github"
    url = "https://github.com/laixintao/iredis"
    weight = 2
  [[menu.nav]]
    name = "Bugs"
    pre = "info"
    url = "https://github.com/laixintao/iredis/issues"
    weight = 3

[params]
  includeBootstrapJs = false
  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Welcome to the Vanilla theme demo. Have a look around. Maybe even eat some ice cream."
  footerText = "Another software created by [laixintao](http://github.com/laixintao/)"
  hideFooter = false
